# 1. What is PCA?
**Definition:** 
1. PCA is a dimensionality reduction algorithm. It tries to reduce the dimension while retaining most of the original information.
2. Creation of new variables using old variables which would mean they are a combination of old variables and are uncorrelated to each other which simplifies the analysis.
3. Helps in plotting high dimensional data to lower dimension, say scatter plot in 3d using plotly. 

**Working:** 
1. Standardize or scale the input features.
2. Find covariance matrix
3. Find Eigen Values and Eigen Vectors

In [ ]:
from sklearn.datasets import make_blobs
import numpy as np
import pandas as pd

data = make_blobs(n_samples=50, n_features=3, shuffle=True)
input = np.array(data[0])
output = np.array(data[1])
# input
# output

input_df = pd.DataFrame({
    'feature_1': input[:, 0],
    'feature_2': input[:, 1],
    'feature_3': input[:, 2],
    'label': output
})
input_df.describe()

In [28]:
# Step-2: Covariance matrix creation
cov_matrix = np.cov([input_df.iloc[:,0], input_df.iloc[:,1], input_df.iloc[:,2]])
cov_matrix

array([[  9.09865093,  -6.79107097,   7.59248356],
       [ -6.79107097,  53.19675351, -30.79560363],
       [  7.59248356, -30.79560363,  20.87085887]])

In [29]:
# Step-3: Get eigen values and eigen vector
eigen_values, eigen_vectors = np.linalg.eig(cov_matrix)
eigen_values, eigen_vectors

(array([73.29380796,  8.92528264,  0.94717271]),
 array([[-0.15028506,  0.90383686, -0.40061618],
        [ 0.8427797 ,  0.32896694,  0.42603185],
        [-0.51685277,  0.27360496,  0.81117417]]))